name: Unscramble
author: Hotshot2162
authors: ["Hotshot2162", "xxxTeslaxxx"]
version: 4.0
main: xxxteslaxxx.chris.unscramble.UnscrambleMain
description: A plugin that creates unscramble games in server chat for players to have some fun.
depend: [Vault, Essentials]
commands:
    unscramble:
        description: This command is the base command for the entire plugin.
        usage: /<command>
    us:
        description: This is the same thing as using unscramble
        usage: /<command>